services:
  - type: web
    name: concept-crack
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    autoDeploy: true
    branch: dev
    envVars:
      - key: VITE_GEMINI_API_KEY
        sync: false
