/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#454652',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#767683',
        'outline-variant': '#c6c5d4',
        'surface-tint': '#4c56af',
        primary: {
          DEFAULT: '#000666',
          container: '#1a237e',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#8690ee',
        'inverse-primary': '#bdc2ff',
        secondary: {
          DEFAULT: '#632ce5',
          container: '#7c4dff',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fcf6ff',
        tertiary: {
          DEFAULT: '#00201a',
          container: '#00372e',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#00ab93',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary-fixed': '#000767',
        'on-primary-fixed-variant': '#343d96',
        'secondary-fixed': '#e8deff',
        'secondary-fixed-dim': '#cdbdff',
        'on-secondary-fixed': '#20005f',
        'on-secondary-fixed-variant': '#4f00d0',
        'tertiary-fixed': '#68fadd',
        'tertiary-fixed-dim': '#44ddc1',
        'on-tertiary-fixed': '#00201a',
        'on-tertiary-fixed-variant': '#005145',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        'unit': '8px',
        'gutter': '24px',
        'card': '24px',
        'container-desktop': '32px',
        'container-mobile': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
      boxShadow: {
        'elev-1': '0 1px 2px rgba(0,0,0,0.04)',
        'elev-2': '0 4px 12px rgba(0,0,0,0.08)',
        'elev-3': '0 12px 32px rgba(0,0,0,0.16)',
      },
    },
  },
  plugins: [],
};
