#!/usr/bin/env python3
"""
Backfills the "uniqueId" registration-number field (e.g. "STU000042") onto
every existing user document that doesn't have one yet — the app itself only
assigns one at account-creation time or lazily on next login, so accounts
created before this feature shipped need a one-time catch-up.

One counter per role, in Firestore doc counters/users_<role>, matching
src/lib/userIds.ts's scheme exactly (same prefix map, same padding) so IDs
generated here and IDs generated by the live app never collide or diverge.

Dry-run by default — only prints what it would assign. Pass --execute to
actually write. Existing users already keep whatever they have; this never
overwrites a uniqueId that's already set.

Run:  python backfill_user_ids.py --service-account service-account.json [--execute]
"""

import argparse
import sys
from pathlib import Path

import firebase_admin
from firebase_admin import credentials, firestore

PREFIX = {
    "student": "STU",
    "parent":  "PAR",
    "faculty": "FAC",
    "admin":   "ADM",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--service-account", default="service-account.json")
    ap.add_argument("--execute", action="store_true")
    args = ap.parse_args()

    sa_path = Path(args.service_account)
    if not sa_path.exists():
        print(f"{sa_path} not found.")
        sys.exit(1)

    cred = credentials.Certificate(str(sa_path))
    app = firebase_admin.initialize_app(cred)
    db = firestore.client(app=app)

    print("Scanning users/ for accounts missing uniqueId...\n")
    users = list(db.collection("users").stream())
    print(f"  {len(users)} total user doc(s)")

    # Start each role's counter from whatever's already in Firestore (in case
    # the live app has already assigned some IDs via login/admin-create since
    # this feature shipped) so we never reissue a number that's in use.
    counters = {}
    for role, prefix in PREFIX.items():
        counter_ref = db.collection("counters").document(f"users_{role}")
        snap = counter_ref.get()
        counters[role] = snap.to_dict().get("seq", 0) if snap.exists else 0

    missing = [u for u in users if not (u.to_dict() or {}).get("uniqueId")]
    print(f"  {len(missing)} user(s) missing a uniqueId\n")

    assignments = []  # (doc_id, role, name, email, new_id)
    for u in missing:
        data = u.to_dict() or {}
        role = data.get("role")
        if role not in PREFIX:
            print(f"  SKIP {u.id} — unrecognized/missing role {role!r}")
            continue
        counters[role] += 1
        new_id = f"{PREFIX[role]}{counters[role]:06d}"
        assignments.append((u.id, role, data.get("name", "?"), data.get("email", "?"), new_id))

    print(f"{'Would assign' if not args.execute else 'Assigning'} {len(assignments)} ID(s):\n")
    for doc_id, role, name, email, new_id in assignments:
        print(f"  {new_id}  {role:8s} {name:30s} {email}")

    if not args.execute:
        print("\nDRY RUN — nothing written. Re-run with --execute to apply.")
        return

    batch = db.batch()
    batch_count = 0
    for doc_id, role, name, email, new_id in assignments:
        batch.set(db.collection("users").document(doc_id), {"uniqueId": new_id}, merge=True)
        batch_count += 1
        if batch_count >= 400:
            batch.commit()
            batch = db.batch()
            batch_count = 0
    if batch_count:
        batch.commit()

    for role, prefix in PREFIX.items():
        db.collection("counters").document(f"users_{role}").set({"seq": counters[role]}, merge=True)

    print(f"\nDone — {len(assignments)} user(s) updated, counters saved.")


if __name__ == "__main__":
    main()
