#!/usr/bin/env python3
"""
PrepMind — Finalize a subject's re-imported question bank
=============================================================
Once a subject's "<Chapter> (New)" staging import has been verified good,
this collapses it into the single canonical version:
  1. Deletes the old, superseded ALLEN-sourced docs for that subject (ONLY
     for the exact chapter names that have a verified "(New)" replacement —
     never a broad subject-wide delete, since some subjects also have large,
     completely unrelated pre-existing question banks under other source
     tags that must never be touched).
  2. Deletes the old `chapters/` doc for each of those chapter names.
  3. Strips the " (New)" suffix from the new docs' chapter/topic fields.
  4. Leaves the `chapters/` collection to be regenerated by
     refresh_chapters_from_firestore.py afterward.

Defaults to a DRY RUN (reports counts, changes nothing). Pass --execute to
actually perform the deletes/renames.

Run:
  python finalize_subject.py Physics --new-source "Physics Question Bank v2" --service-account service-account.json
  python finalize_subject.py Physics --new-source "Physics Question Bank v2" --service-account service-account.json --execute
"""

import argparse
import sys
from collections import Counter

import firebase_admin
from firebase_admin import credentials, firestore

BATCH_SIZE = 400


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("subject")
    ap.add_argument("--new-source", required=True, help='exact source tag of the new "(New)" docs, e.g. "Physics Question Bank v2"')
    ap.add_argument("--old-source", default="ALLEN", help="exact source tag of the old docs to retire (default: ALLEN)")
    ap.add_argument("--service-account", default="service-account.json")
    ap.add_argument("--execute", action="store_true", help="actually perform the deletes/renames (default: dry run)")
    args = ap.parse_args()

    cred = credentials.Certificate(args.service_account)
    app = firebase_admin.initialize_app(cred)
    db = firestore.client(app=app)

    subject = args.subject

    print(f"Scanning '{subject}' docs ...")
    new_docs = list(db.collection("questions")
                     .where(filter=firestore.FieldFilter("subject", "==", subject))
                     .where(filter=firestore.FieldFilter("source", "==", args.new_source))
                     .stream())
    old_docs = list(db.collection("questions")
                     .where(filter=firestore.FieldFilter("subject", "==", subject))
                     .where(filter=firestore.FieldFilter("source", "==", args.old_source))
                     .stream())

    new_chapters = Counter(d.to_dict().get("chapter", "") for d in new_docs)
    old_chapters = Counter(d.to_dict().get("chapter", "") for d in old_docs)

    def norm(s):
        import re
        # Strip a leading "N." / "N " / "N_" chapter-number prefix (old Biology
        # chapter names carry this, e.g. "7.EVOLUTION"; old Physics chapter
        # names don't) before the alnum-only comparison — but only a LEADING
        # prefix, since trailing digits are sometimes meaningful and distinct
        # (e.g. "Gravitation 1" vs "Gravitation 2" are different chapters).
        s = re.sub(r'^\d+[\._\-\s]+', '', s)
        return "".join(ch for ch in s.lower() if ch.isalnum())

    new_by_norm = {}
    for ch in new_chapters:
        stripped = ch[:-len(" (New)")] if ch.endswith(" (New)") else ch
        new_by_norm[norm(stripped)] = ch

    # Only retire an old chapter if it has an exact, unambiguous "(New)" counterpart.
    matched_old_chapters = []
    unmatched_old = []
    for ch in old_chapters:
        if norm(ch) in new_by_norm:
            matched_old_chapters.append(ch)
        else:
            unmatched_old.append(ch)

    matched_new_chapters = {new_by_norm[norm(ch)] for ch in matched_old_chapters}
    unmatched_new = [ch for ch in new_chapters if ch not in matched_new_chapters]

    old_to_delete = [d for d in old_docs if d.to_dict().get("chapter", "") in matched_old_chapters]

    print(f"\n{'=' * 60}")
    print(f"Subject: {subject}")
    print(f"  New ('{args.new_source}') docs total : {len(new_docs)} across {len(new_chapters)} chapters")
    print(f"  Old ('{args.old_source}') docs total  : {len(old_docs)} across {len(old_chapters)} chapters")
    print(f"  Matched chapter pairs               : {len(matched_old_chapters)}")
    print(f"  Old docs that WILL be deleted        : {len(old_to_delete)}")
    if unmatched_old:
        print(f"  WARNING — old chapters with NO '(New)' match (left untouched): {unmatched_old}")
    if unmatched_new:
        print(f"  WARNING — new chapters with NO old match found: {unmatched_new}")

    if not args.execute:
        print("\nDRY RUN — nothing changed. Re-run with --execute to apply.")
        return

    if unmatched_old or unmatched_new:
        print("\nRefusing to --execute while there are unmatched chapters above — resolve first.")
        sys.exit(1)

    print("\nDeleting old docs ...")
    for i in range(0, len(old_to_delete), BATCH_SIZE):
        batch = db.batch()
        for d in old_to_delete[i:i + BATCH_SIZE]:
            batch.delete(d.reference)
        batch.commit()
        print(f"  deleted {min(i + BATCH_SIZE, len(old_to_delete))}/{len(old_to_delete)}")

    print("\nDeleting old chapter docs ...")
    for ch in matched_old_chapters:
        safe_id = f"{subject}_{ch}".replace(" ", "_").replace("/", "-")[:100]
        db.collection("chapters").document(safe_id).delete()
    print(f"  deleted {len(matched_old_chapters)} chapter doc(s)")

    print("\nRenaming new docs (stripping ' (New)' suffix) ...")
    for i in range(0, len(new_docs), BATCH_SIZE):
        batch = db.batch()
        for d in new_docs[i:i + BATCH_SIZE]:
            data = d.to_dict()
            chapter = data.get("chapter", "")
            if chapter.endswith(" (New)"):
                clean = chapter[:-len(" (New)")]
                batch.update(d.reference, {"chapter": clean, "topic": clean})
        batch.commit()
        print(f"  renamed {min(i + BATCH_SIZE, len(new_docs))}/{len(new_docs)}")

    print(f"\nDone. Now run: python refresh_chapters_from_firestore.py {args.service_account}")


if __name__ == "__main__":
    main()
